### ISSUE TITLE
some dead links

### ISSUE THREAD

**Issue by maskersss** [sathya-pramodh/linux-mcsr#11]
https://sathya-pramodh.github.io/linux-mcsr/perf/jemalloc_glfw.html : the "here" jemalloc link links to a 404, https://github.com/tesselslate/resetti/blob/main/doc/optimization.md#malloc-improvements looks like the right link to me

https://sathya-pramodh.github.io/linux-mcsr/splitting-audio.html : bottom of the page, dead link to resetticord ; "You can go here to continue with the post install instructions." the `here` is also dead

**Comment by ohnishant** [comment]
Thanks for these!
