### ISSUE TITLE
Issues with audio splitting setup

### ISSUE THREAD

**Issue by draconix6** [sathya-pramodh/linux-mcsr#2]
- [qpwgraph having only two nodes](https://cdn.discordapp.com/attachments/817165102985510933/1149867551245991996/image.png) (at the "Setting up audio splits" point in the doc)
wasn't exactly sure how i got this solved, i remember messing with it and giving up then the next morning it was working. something to do with pulseaudio/pipewire installation, [this](https://github.com/mikeroyal/PipeWire-Guide#installing-pipewire-for-debian) was probably what fixed it but don't quote me on it, can try do more testing

- OBS hanging when adding the JACK audio sources
fixed by installing OBS thru github, flatpak version didn't work
after adding the JACK sources on this version, qpwgraph didn't show OBS inputs in accordance with the JACK sources - i instead added [Audio Input Capture (PulseAudio)](https://cdn.discordapp.com/attachments/817165102985510933/1149871039862538321/image.png) sources, which show up on qpwgraph just fine (albeit using my mic by default). not sure if this is a bad way of doing it since i hear pulseaudio/pipewire are like, not the same lol

**Comment by draconix6** [comment]
^oh yeah, since the virtual inputs aren't connected to anything i'm not even convinced they were necessary to getting it working (spotify, minecrafts, etc are just connected directly to OBS nodes), i kinda freestyled the qpwgraph setup tbf but i'll let u know if anything else breaks

**Comment by sathya-pramodh** [comment]
Oh yeah uhhh the first error was definitely not having pipewire-pulse. Idk why the second error happens tbf... afaik Audio Input Capture (PulseAudio) shouldn't change anything but that's interesting, gotta experiment with that. The JACK sources method worked for me with OBS on flatpak.
Directly connecting the sources to OBS nodes is fine.. I liked the Virtual Inputs way because you can set the default audio source in pavucontrol (or any audio controlling application) to be any of the Virtual Input and essentially any new audio source that is connected to the PC would get routed through that. But if it works it works. Let me know if the OBS nodes method was easier!

**Comment by draconix6** [comment]
i started using virtual inputs regardless just so qpwgraph was tidier, not using any audio controllers or anything just yet. other than it being laid out nicer i don't think there's any upside/downside to either method in my case, however using audio input capture sources are annoying since on reboot they'll default to using my mic and i have to remember to disconnect the nodes in qpwgraph manually. nbd at this point it's less hassle than windows splitting lole

**Comment by sathya-pramodh** [comment]
That's interesting to hear. I thought this was so much more of a hassle as compared to Windows where in Windows, OBS comes with a direct source which you can add to it that captures Application Outputs. 
As for the JACK input source crashing OBS, could you run OBS in a terminal (the flatpak version) by running `flatpak run com.obsproject.Studio` and check if it points to anything before crashing? I'm kinda assuming its gonna be something related to `alsa-jack` or something missing, but I'm not really sure.

**Comment by sathya-pramodh** [comment]
Closing this issue cause' its super old :D
